### ISSUE TITLE
Page produit ( client )

### ISSUE THREAD

**Issue by DEVPEG2024** [DEVPEG2024/PEG_FRONTEND#51]
Cette page ne s'affiche pas : 

https://app.mypeg.fr/customer/product/6714e5b0b1e0969ef952bc90

Elle apparaît bien chez le client, mais lorsqu'on clique, une page s'ouvre et rien ne se passe.

**Comment by DEVPEG2024** [comment]
Le panier du client connait le meme problème

**Comment by mguldner** [comment]
Suite à analyse, la solution utilisée à la création du projet pour le stockage des images n'est pas adaptée.
En effet, les images ne sont pas persistées via Heroku: en cas de redémarrage du serveur, les images sont perdues.

Le passage par un service tiers (type cloudinary) est à privilégier.
