### ISSUE TITLE
Mot de passe 

### ISSUE THREAD

**Issue by DEVPEG2024** [DEVPEG2024/PEG_FRONTEND#7]
Je ne peux pas accéder à cette page : https://app.mypeg.fr/settings/password

**Comment by DEVPEG2024** [comment]
Même en te connectant sur [https://app.mypeg.fr](https://app.mypeg.fr)
Puis en allant sur "paramètres" et onglet "mot de passe" ?
Je n'ai pas le souci de mon côté.

**Comment by mguldner** [comment]
As-tu le problème en te connectant sur https://app.mypeg.fr
Puis en allant sur "paramètres" et onglet "mot de passe" ?
Je n'ai pas le souci de mon côté.
